### ISSUE TITLE
Load all configurations

### ISSUE THREAD

**Issue by holzon** [techsoft3d/ExchangeToolkit#11]
I'm having some trouble reading all configurations using
m_sSpecifics.m_sSolidworks.m_bLoadAllConfigsData = true;

I traverse all representation items with
        auto leaf_instances = ts3d::getLeafInstances(model, kA3DTypeRiRepresentationItem);
        
I get the correct number of configurations and matching names during traversal when I check                     
ts3d::A3DAsmProductOccurrenceWrapper po_data(instance.leaf());
bool is_configuration = po_data->m_uiProductFlags & A3D_PRODUCT_FLAG_CONFIG;

The actual traversed data seem to end up the same though, in my case I get 3 identical models instead of them being configured differently (as seen in the HOOPS Demo Viewer)

Am I being too optimistic, or is there a way to use the ExchangeToolkit while reading all configurations?

**Comment by bflubacherts3d** [comment]
Hello Holzon,
The ExchangeToolkit does not add or remove any core functionality or behaviors, so if you're able to see the result you're after in the demo view, you should be able to achieve it with the API directly and/or through the use of helper objects in the ExchangeToolkit.

The Demo Viewer is loading the file and enumerating the configurations, displaying the result in the "Configurations" tab of the Model Browser. When you double click on a configuration, the demo viewer uses the [A3DRWParamsMultiEntriesData](https://docs.techsoft3d.com/exchange/latest/build/struct_a3_d_r_w_params_multi_entries_data.html) option to specify the specific configuration to load.

Having said that, what you're using should work to load *all* configurations. When I use the "Viewer" sample (ships with Exchange in the samples folder) and I modify the load params to include all SolidWorks configurations (as you've detailed), I see all configurations of the input file simultaneously in the view.  So, I'm seeing what you're after. 

Here is the input assembly I've used to test: https://grabcad.com/library/my-coffee-table-2

Perhaps there's something going on with your input assembly. I believe there may be cases where configurations may need to be re-generated and explicitly saved. Please take a look at this knowledge base article for more information:

https://techsoft3d.atlassian.net/servicedesk/customer/portal/7/article/819265659?src=-1458646309

Thanks,
Brad

**Comment by holzon** [comment]
Oh man, looks like I was having a bad Friday, got stuck looking for this for hours and it was all on my own end, was happily writing out the first config multiple times 🤦 
Thanks a lot for pointing me in the right direction, working great now!!! 🥳
