### ISSUE TITLE
Can someone review if the getMatrix function in ExchangeEigenBridge.h line 103

### ISSUE THREAD

**Issue by steven-belbin** [techsoft3d/ExchangeToolkit#16]
When the entity type is of type kA3DTypeMiscGeneralTransformation at line 103 of the getMatrix function (see below)

Should in fact be returning an identity matrix which is at the end of this function?

The reason is that there is a getMatrixFromGeneralTransformation which is implemented within the same header but isn't invoked in this scenario.

[GetMatrix line #103](https://github.com/techsoft3d/ExchangeToolkit/blob/master/ExchangeToolkit/include/ExchangeEigenBridge.h#L103)

```c++
case kA3DTypeMiscGeneralTransformation:
    break;
    return getMatrixFromGeneralTransformation(xform);
```

**Comment by cpillion** [comment]
Hi Steven,

Thank you for bringing this to our attention. 
No, it should not be breaking out of this case and returning the Identity matrix. It should return the General Transformation information, just like in the Cartesian case. The `break` and `return` statements can be swapped, or the `break` removed. I have submitted a pull request with this change. 

Thanks for your feedback!

Chris

**Comment by steven-belbin** [comment]
@cpillion 
Thanks for the fix.
